### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by achoruzy** [achoruzy/Cgameoflife#1]
## General plan for the project ##

- [x] Game grid
    - [x] main window + scalability + fullscreen
    - [x] drawing grid
    - [x] drawing cells
    - [x] input for grid management
    - [x] mouse hoover
- [x] Game logic
    - [x] convay's rules implementation
    - [x] grid end repetition / insta death
- [x] Basic user gameplay
    - [x] spawning cells on click
- [x] UI
    - [x] UI for user gameplay + logic
- [x] Visuals
    - [x] cell color rules implementation
    - [x] postprocessing
- [x] Audio
